/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_inscription (void)
{
  GtkWidget *inscription;
  GtkWidget *fixed1;
  GtkWidget *entry1_nom;
  GtkWidget *entry2_Mot;
  GtkWidget *button1_inscription;
  GtkWidget *label1_nom;
  GtkWidget *label2_mot;

  inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscription), _("inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (inscription), fixed1);

  entry1_nom = gtk_entry_new ();
  gtk_widget_show (entry1_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1_nom, 184, 48);
  gtk_widget_set_size_request (entry1_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_nom), 8226);

  entry2_Mot = gtk_entry_new ();
  gtk_widget_show (entry2_Mot);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2_Mot, 184, 104);
  gtk_widget_set_size_request (entry2_Mot, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entry2_Mot), 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_Mot), 8226);

  button1_inscription = gtk_button_new_with_mnemonic (_("inscription"));
  gtk_widget_show (button1_inscription);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_inscription, 448, 304);
  gtk_widget_set_size_request (button1_inscription, 104, 48);

  label1_nom = gtk_label_new (_("Nom"));
  gtk_widget_show (label1_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), label1_nom, 40, 48);
  gtk_widget_set_size_request (label1_nom, 41, 17);

  label2_mot = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label2_mot);
  gtk_fixed_put (GTK_FIXED (fixed1), label2_mot, 16, 104);
  gtk_widget_set_size_request (label2_mot, 120, 16);

  g_signal_connect ((gpointer) button1_inscription, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscription, inscription, "inscription");
  GLADE_HOOKUP_OBJECT (inscription, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (inscription, entry1_nom, "entry1_nom");
  GLADE_HOOKUP_OBJECT (inscription, entry2_Mot, "entry2_Mot");
  GLADE_HOOKUP_OBJECT (inscription, button1_inscription, "button1_inscription");
  GLADE_HOOKUP_OBJECT (inscription, label1_nom, "label1_nom");
  GLADE_HOOKUP_OBJECT (inscription, label2_mot, "label2_mot");

  return inscription;
}

GtkWidget*
create_authen (void)
{
  GtkWidget *authen;
  GtkWidget *fixed2;
  GtkWidget *entry4_login;
  GtkWidget *entry5_Pw;
  GtkWidget *label5_Pw;
  GtkWidget *label4_login;
  GtkWidget *button2_authen;

  authen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authen), _("authentification"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (authen), fixed2);

  entry4_login = gtk_entry_new ();
  gtk_widget_show (entry4_login);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4_login, 232, 104);
  gtk_widget_set_size_request (entry4_login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_login), 8226);

  entry5_Pw = gtk_entry_new ();
  gtk_widget_show (entry5_Pw);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5_Pw, 232, 192);
  gtk_widget_set_size_request (entry5_Pw, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_Pw), 8226);

  label5_Pw = gtk_label_new (_("password"));
  gtk_widget_show (label5_Pw);
  gtk_fixed_put (GTK_FIXED (fixed2), label5_Pw, 56, 200);
  gtk_widget_set_size_request (label5_Pw, 88, 16);

  label4_login = gtk_label_new (_("login"));
  gtk_widget_show (label4_login);
  gtk_fixed_put (GTK_FIXED (fixed2), label4_login, 48, 113);
  gtk_widget_set_size_request (label4_login, 57, 16);

  button2_authen = gtk_button_new_with_mnemonic (_("ok"));
  gtk_widget_show (button2_authen);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_authen, 224, 304);
  gtk_widget_set_size_request (button2_authen, 192, 40);

  g_signal_connect ((gpointer) button2_authen, "clicked",
                    G_CALLBACK (on_button2_authen_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authen, authen, "authen");
  GLADE_HOOKUP_OBJECT (authen, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (authen, entry4_login, "entry4_login");
  GLADE_HOOKUP_OBJECT (authen, entry5_Pw, "entry5_Pw");
  GLADE_HOOKUP_OBJECT (authen, label5_Pw, "label5_Pw");
  GLADE_HOOKUP_OBJECT (authen, label4_login, "label4_login");
  GLADE_HOOKUP_OBJECT (authen, button2_authen, "button2_authen");

  return authen;
}

GtkWidget*
create_espace_foyer (void)
{
  GtkWidget *espace_foyer;
  GtkWidget *fixed3;
  GtkWidget *treeview4;
  GtkWidget *button1_dec;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image24;
  GtkWidget *label52;
  GtkWidget *button_calculement;
  GtkWidget *button1_af;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image23;
  GtkWidget *label51;
  GtkWidget *button1_rech;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label29;
  GtkWidget *button1_mod;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label17;
  GtkWidget *button4_supp;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label16;
  GtkWidget *button3_ajouter;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *EMTlabel31;
  GtkWidget *image25;

  espace_foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_foyer), _("Espace Foyer"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (espace_foyer), fixed3);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview4, 152, 200);
  gtk_widget_set_size_request (treeview4, 592, 328);

  button1_dec = gtk_button_new ();
  gtk_widget_show (button1_dec);
  gtk_fixed_put (GTK_FIXED (fixed3), button1_dec, 616, 0);
  gtk_widget_set_size_request (button1_dec, 114, 24);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button1_dec), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image24 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox20), image24, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox20), label52, FALSE, FALSE, 0);

  button_calculement = gtk_button_new_with_mnemonic (_("calcul"));
  gtk_widget_show (button_calculement);
  gtk_fixed_put (GTK_FIXED (fixed3), button_calculement, 48, 488);
  gtk_widget_set_size_request (button_calculement, 66, 29);

  button1_af = gtk_button_new ();
  gtk_widget_show (button1_af);
  gtk_fixed_put (GTK_FIXED (fixed3), button1_af, 0, 424);
  gtk_widget_set_size_request (button1_af, 152, 56);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button1_af), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox19), image23, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("affichage"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox19), label51, FALSE, FALSE, 0);

  button1_rech = gtk_button_new ();
  gtk_widget_show (button1_rech);
  gtk_fixed_put (GTK_FIXED (fixed3), button1_rech, 0, 368);
  gtk_widget_set_size_request (button1_rech, 152, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button1_rech), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox15), label29, FALSE, FALSE, 0);

  button1_mod = gtk_button_new ();
  gtk_widget_show (button1_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), button1_mod, 0, 312);
  gtk_widget_set_size_request (button1_mod, 152, 56);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button1_mod), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox9), label17, FALSE, FALSE, 0);

  button4_supp = gtk_button_new ();
  gtk_widget_show (button4_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), button4_supp, 0, 256);
  gtk_widget_set_size_request (button4_supp, 152, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button4_supp), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox8), label16, FALSE, FALSE, 0);

  button3_ajouter = gtk_button_new ();
  gtk_widget_show (button3_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), button3_ajouter, 0, 200);
  gtk_widget_set_size_request (button3_ajouter, 152, 56);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button3_ajouter), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  EMTlabel31 = gtk_label_new (_("<span foreground=\"red\"><b>Bienvenue dans l'Espace Foyer </b></span>"));
  gtk_widget_show (EMTlabel31);
  gtk_fixed_put (GTK_FIXED (fixed3), EMTlabel31, 184, 96);
  gtk_widget_set_size_request (EMTlabel31, 416, 24);
  gtk_label_set_use_markup (GTK_LABEL (EMTlabel31), TRUE);

  image25 = create_pixmap (espace_foyer, "index.jpeg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed3), image25, 0, 0);
  gtk_widget_set_size_request (image25, 192, 184);

  g_signal_connect ((gpointer) treeview4, "row_activated",
                    G_CALLBACK (on_treeview4_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1_dec, "clicked",
                    G_CALLBACK (on_button1_dec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_calculement, "clicked",
                    G_CALLBACK (on_button_calculement_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_af, "clicked",
                    G_CALLBACK (on_button1_af_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_rech, "clicked",
                    G_CALLBACK (on_button1_rech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_mod, "clicked",
                    G_CALLBACK (on_button1_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_supp, "clicked",
                    G_CALLBACK (on_button4_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_ajouter, "clicked",
                    G_CALLBACK (on_button3_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_foyer, espace_foyer, "espace_foyer");
  GLADE_HOOKUP_OBJECT (espace_foyer, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (espace_foyer, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (espace_foyer, button1_dec, "button1_dec");
  GLADE_HOOKUP_OBJECT (espace_foyer, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (espace_foyer, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (espace_foyer, image24, "image24");
  GLADE_HOOKUP_OBJECT (espace_foyer, label52, "label52");
  GLADE_HOOKUP_OBJECT (espace_foyer, button_calculement, "button_calculement");
  GLADE_HOOKUP_OBJECT (espace_foyer, button1_af, "button1_af");
  GLADE_HOOKUP_OBJECT (espace_foyer, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (espace_foyer, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (espace_foyer, image23, "image23");
  GLADE_HOOKUP_OBJECT (espace_foyer, label51, "label51");
  GLADE_HOOKUP_OBJECT (espace_foyer, button1_rech, "button1_rech");
  GLADE_HOOKUP_OBJECT (espace_foyer, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (espace_foyer, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (espace_foyer, image15, "image15");
  GLADE_HOOKUP_OBJECT (espace_foyer, label29, "label29");
  GLADE_HOOKUP_OBJECT (espace_foyer, button1_mod, "button1_mod");
  GLADE_HOOKUP_OBJECT (espace_foyer, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (espace_foyer, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (espace_foyer, image9, "image9");
  GLADE_HOOKUP_OBJECT (espace_foyer, label17, "label17");
  GLADE_HOOKUP_OBJECT (espace_foyer, button4_supp, "button4_supp");
  GLADE_HOOKUP_OBJECT (espace_foyer, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (espace_foyer, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (espace_foyer, image8, "image8");
  GLADE_HOOKUP_OBJECT (espace_foyer, label16, "label16");
  GLADE_HOOKUP_OBJECT (espace_foyer, button3_ajouter, "button3_ajouter");
  GLADE_HOOKUP_OBJECT (espace_foyer, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (espace_foyer, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (espace_foyer, image7, "image7");
  GLADE_HOOKUP_OBJECT (espace_foyer, label15, "label15");
  GLADE_HOOKUP_OBJECT (espace_foyer, EMTlabel31, "EMTlabel31");
  GLADE_HOOKUP_OBJECT (espace_foyer, image25, "image25");

  return espace_foyer;
}

GtkWidget*
create_ajout (void)
{
  GtkWidget *ajout;
  GtkWidget *fixed4;
  GtkWidget *entry6_Nom;
  GtkWidget *entry7_Pr;
  GtkWidget *entry8_cin;
  GtkWidget *entry9_ch;
  GtkWidget *label9_chambre;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *entry1_email;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *button5_ajouter;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image18;
  GtkWidget *label36;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8_cin;
  GtkWidget *button1_afficher;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image20;
  GtkWidget *label39;
  GtkWidget *label44;
  GtkWidget *combobox1;
  GtkWidget *combobox3;
  GtkWidget *error;

  ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout), _("ajout"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (ajout), fixed4);

  entry6_Nom = gtk_entry_new ();
  gtk_widget_show (entry6_Nom);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6_Nom, 184, 80);
  gtk_widget_set_size_request (entry6_Nom, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6_Nom), 8226);

  entry7_Pr = gtk_entry_new ();
  gtk_widget_show (entry7_Pr);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7_Pr, 184, 128);
  gtk_widget_set_size_request (entry7_Pr, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7_Pr), 8226);

  entry8_cin = gtk_entry_new ();
  gtk_widget_show (entry8_cin);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8_cin, 184, 32);
  gtk_widget_set_size_request (entry8_cin, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8_cin), 8226);

  entry9_ch = gtk_entry_new ();
  gtk_widget_show (entry9_ch);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9_ch, 184, 168);
  gtk_widget_set_size_request (entry9_ch, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9_ch), 8226);

  label9_chambre = gtk_label_new (_("CHAMBRE :"));
  gtk_widget_show (label9_chambre);
  gtk_fixed_put (GTK_FIXED (fixed4), label9_chambre, 32, 176);
  gtk_widget_set_size_request (label9_chambre, 80, 16);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 176, 224);
  gtk_widget_set_size_request (spinbutton1, 56, 32);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 232, 224);
  gtk_widget_set_size_request (spinbutton2, 72, 32);

  spinbutton3_adj = gtk_adjustment_new (1, 1996, 2015, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 304, 224);
  gtk_widget_set_size_request (spinbutton3, 64, 32);

  label32 = gtk_label_new (_("Date naiss ( j/m/a):"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 8, 216);
  gtk_widget_set_size_request (label32, 176, 40);

  label33 = gtk_label_new (_("sexe:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 0, 280);
  gtk_widget_set_size_request (label33, 120, 16);

  entry1_email = gtk_entry_new ();
  gtk_widget_show (entry1_email);
  gtk_fixed_put (GTK_FIXED (fixed4), entry1_email, 128, 328);
  gtk_widget_set_size_request (entry1_email, 264, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_email), 8226);

  label34 = gtk_label_new (_("email:"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 24, 328);
  gtk_widget_set_size_request (label34, 80, 24);

  label35 = gtk_label_new (_("methode de paiement:"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 24, 376);
  gtk_widget_set_size_request (label35, 160, 32);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton1, 128, 280);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton2, 256, 280);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  button5_ajouter = gtk_button_new ();
  gtk_widget_show (button5_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), button5_ajouter, 416, 208);
  gtk_widget_set_size_request (button5_ajouter, 104, 64);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button5_ajouter), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox16), image18, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox16), label36, FALSE, FALSE, 0);

  label6 = gtk_label_new (_("NOM:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 48, 88);
  gtk_widget_set_size_request (label6, 41, 17);

  label7 = gtk_label_new (_("PRENOM:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed4), label7, 40, 136);
  gtk_widget_set_size_request (label7, 72, 16);

  label8_cin = gtk_label_new (_("CIN:"));
  gtk_widget_show (label8_cin);
  gtk_fixed_put (GTK_FIXED (fixed4), label8_cin, 48, 40);
  gtk_widget_set_size_request (label8_cin, 41, 17);

  button1_afficher = gtk_button_new ();
  gtk_widget_show (button1_afficher);
  gtk_fixed_put (GTK_FIXED (fixed4), button1_afficher, 416, 280);
  gtk_widget_set_size_request (button1_afficher, 104, 64);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button1_afficher), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox18), image20, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox18), label39, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("niveau"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 16, 432);
  gtk_widget_set_size_request (label44, 104, 24);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1, 208, 376);
  gtk_widget_set_size_request (combobox1, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("semestriel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("trimestriel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("annuel"));

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox3, 120, 424);
  gtk_widget_set_size_request (combobox3, 48, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("5"));

  error = gtk_label_new ("");
  gtk_widget_show (error);
  gtk_fixed_put (GTK_FIXED (fixed4), error, 360, 104);
  gtk_widget_set_size_request (error, 184, 25);
  gtk_label_set_use_markup (GTK_LABEL (error), TRUE);

  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) button5_ajouter, "clicked",
                    G_CALLBACK (on_button5_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_afficher, "clicked",
                    G_CALLBACK (on_button1_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (ajout, entry6_Nom, "entry6_Nom");
  GLADE_HOOKUP_OBJECT (ajout, entry7_Pr, "entry7_Pr");
  GLADE_HOOKUP_OBJECT (ajout, entry8_cin, "entry8_cin");
  GLADE_HOOKUP_OBJECT (ajout, entry9_ch, "entry9_ch");
  GLADE_HOOKUP_OBJECT (ajout, label9_chambre, "label9_chambre");
  GLADE_HOOKUP_OBJECT (ajout, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajout, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajout, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajout, label32, "label32");
  GLADE_HOOKUP_OBJECT (ajout, label33, "label33");
  GLADE_HOOKUP_OBJECT (ajout, entry1_email, "entry1_email");
  GLADE_HOOKUP_OBJECT (ajout, label34, "label34");
  GLADE_HOOKUP_OBJECT (ajout, label35, "label35");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajout, button5_ajouter, "button5_ajouter");
  GLADE_HOOKUP_OBJECT (ajout, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (ajout, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajout, image18, "image18");
  GLADE_HOOKUP_OBJECT (ajout, label36, "label36");
  GLADE_HOOKUP_OBJECT (ajout, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajout, label8_cin, "label8_cin");
  GLADE_HOOKUP_OBJECT (ajout, button1_afficher, "button1_afficher");
  GLADE_HOOKUP_OBJECT (ajout, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (ajout, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (ajout, image20, "image20");
  GLADE_HOOKUP_OBJECT (ajout, label39, "label39");
  GLADE_HOOKUP_OBJECT (ajout, label44, "label44");
  GLADE_HOOKUP_OBJECT (ajout, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (ajout, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (ajout, error, "error");

  return ajout;
}

GtkWidget*
create_SUPPRIMER (void)
{
  GtkWidget *SUPPRIMER;
  GtkWidget *fixed5;
  GtkWidget *entry12_CIN;
  GtkWidget *button1_affichersupp;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *button6_supp;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *label13_cin;
  GtkWidget *label_introuvable_supp;

  SUPPRIMER = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (SUPPRIMER), _("supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (SUPPRIMER), fixed5);

  entry12_CIN = gtk_entry_new ();
  gtk_widget_show (entry12_CIN);
  gtk_fixed_put (GTK_FIXED (fixed5), entry12_CIN, 112, 88);
  gtk_widget_set_size_request (entry12_CIN, 160, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12_CIN), 8226);

  button1_affichersupp = gtk_button_new ();
  gtk_widget_show (button1_affichersupp);
  gtk_fixed_put (GTK_FIXED (fixed5), button1_affichersupp, 0, 184);
  gtk_widget_set_size_request (button1_affichersupp, 144, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1_affichersupp), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  button6_supp = gtk_button_new ();
  gtk_widget_show (button6_supp);
  gtk_fixed_put (GTK_FIXED (fixed5), button6_supp, 168, 184);
  gtk_widget_set_size_request (button6_supp, 152, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button6_supp), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("SUPPRIMER"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  label13_cin = gtk_label_new (_("CIN:"));
  gtk_widget_show (label13_cin);
  gtk_fixed_put (GTK_FIXED (fixed5), label13_cin, 32, 88);
  gtk_widget_set_size_request (label13_cin, 72, 32);

  label_introuvable_supp = gtk_label_new ("");
  gtk_widget_show (label_introuvable_supp);
  gtk_fixed_put (GTK_FIXED (fixed5), label_introuvable_supp, 72, 152);
  gtk_widget_set_size_request (label_introuvable_supp, 224, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_introuvable_supp), TRUE);

  g_signal_connect ((gpointer) button1_affichersupp, "clicked",
                    G_CALLBACK (on_button1_affichersupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6_supp, "clicked",
                    G_CALLBACK (on_button6_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SUPPRIMER, SUPPRIMER, "SUPPRIMER");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, entry12_CIN, "entry12_CIN");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, button1_affichersupp, "button1_affichersupp");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, image2, "image2");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, label9, "label9");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, button6_supp, "button6_supp");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, image3, "image3");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, label10, "label10");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, label13_cin, "label13_cin");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, label_introuvable_supp, "label_introuvable_supp");

  return SUPPRIMER;
}

GtkWidget*
create_error (void)
{
  GtkWidget *error;
  GtkWidget *fixed6;
  GtkWidget *label8_error;

  error = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (error), _("error"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (error), fixed6);

  label8_error = gtk_label_new (_("NOT FOUND !!!!!!"));
  gtk_widget_show (label8_error);
  gtk_fixed_put (GTK_FIXED (fixed6), label8_error, 32, 32);
  gtk_widget_set_size_request (label8_error, 184, 72);
  gtk_label_set_justify (GTK_LABEL (label8_error), GTK_JUSTIFY_CENTER);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error, error, "error");
  GLADE_HOOKUP_OBJECT (error, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (error, label8_error, "label8_error");

  return error;
}

GtkWidget*
create_modification (void)
{
  GtkWidget *modification;
  GtkWidget *fixed9;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *chambre;
  GtkWidget *entry1_C;
  GtkWidget *label42;
  GtkWidget *entry2;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *combobox4;
  GtkWidget *combobox5;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label43;
  GtkWidget *label41;
  GtkWidget *label40;
  GtkWidget *label21;
  GtkWidget *label24;
  GtkWidget *label22;
  GtkWidget *label20;
  GtkWidget *button1_r;
  GtkWidget *button2_VAL;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label23;
  GtkWidget *label_introuvable_modif;

  modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modification), _("modification"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (modification), fixed9);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed9), nom, 264, 104);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed9), prenom, 264, 160);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  chambre = gtk_entry_new ();
  gtk_widget_show (chambre);
  gtk_fixed_put (GTK_FIXED (fixed9), chambre, 264, 216);
  gtk_widget_set_size_request (chambre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chambre), 8226);

  entry1_C = gtk_entry_new ();
  gtk_widget_show (entry1_C);
  gtk_fixed_put (GTK_FIXED (fixed9), entry1_C, 264, 48);
  gtk_widget_set_size_request (entry1_C, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_C), 8226);

  label42 = gtk_label_new ("");
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed9), label42, 32, 304);
  gtk_widget_set_size_request (label42, 136, 16);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed9), entry2, 248, 392);
  gtk_widget_set_size_request (entry2, 224, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton4, 264, 352);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton5, 320, 352);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 1994, 2005, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton6, 376, 352);
  gtk_widget_set_size_request (spinbutton6, 72, 24);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton4, 352, 272);
  gtk_widget_set_size_request (radiobutton4, 112, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton3, 256, 272);
  gtk_widget_set_size_request (radiobutton3, 96, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox4, 256, 304);
  gtk_widget_set_size_request (combobox4, 192, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("semestriel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("trimestriel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("annuel"));

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox5, 312, 440);
  gtk_widget_set_size_request (combobox5, 56, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("5"));

  label45 = gtk_label_new (_("email"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed9), label45, 160, 392);
  gtk_widget_set_size_request (label45, 73, 25);

  label46 = gtk_label_new (_("niveau"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed9), label46, 184, 456);
  gtk_widget_set_size_request (label46, 64, 16);

  label43 = gtk_label_new (_("date  de naissance"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed9), label43, 104, 360);
  gtk_widget_set_size_request (label43, 136, 16);

  label41 = gtk_label_new (_("paiement"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed9), label41, 152, 312);
  gtk_widget_set_size_request (label41, 72, 16);

  label40 = gtk_label_new (_("sexe"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed9), label40, 160, 272);
  gtk_widget_set_size_request (label40, 56, 25);

  label21 = gtk_label_new (_("PRENOM"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed9), label21, 144, 160);
  gtk_widget_set_size_request (label21, 73, 24);

  label24 = gtk_label_new (_("CIN"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed9), label24, 152, 48);
  gtk_widget_set_size_request (label24, 64, 24);

  label22 = gtk_label_new (_("CHAMBRE"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed9), label22, 144, 208);
  gtk_widget_set_size_request (label22, 80, 32);

  label20 = gtk_label_new (_("NOM"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed9), label20, 160, 112);
  gtk_widget_set_size_request (label20, 49, 17);

  button1_r = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button1_r);
  gtk_fixed_put (GTK_FIXED (fixed9), button1_r, 488, 240);
  gtk_widget_set_size_request (button1_r, 112, 48);

  button2_VAL = gtk_button_new ();
  gtk_widget_show (button2_VAL);
  gtk_fixed_put (GTK_FIXED (fixed9), button2_VAL, 488, 184);
  gtk_widget_set_size_request (button2_VAL, 112, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button2_VAL), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("VALIDER"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);

  label_introuvable_modif = gtk_label_new ("");
  gtk_widget_show (label_introuvable_modif);
  gtk_fixed_put (GTK_FIXED (fixed9), label_introuvable_modif, 448, 104);
  gtk_widget_set_size_request (label_introuvable_modif, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (label_introuvable_modif), TRUE);

  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) button1_r, "clicked",
                    G_CALLBACK (on_button1_r_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_VAL, "clicked",
                    G_CALLBACK (on_button2_VAL_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modification, modification, "modification");
  GLADE_HOOKUP_OBJECT (modification, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (modification, nom, "nom");
  GLADE_HOOKUP_OBJECT (modification, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (modification, chambre, "chambre");
  GLADE_HOOKUP_OBJECT (modification, entry1_C, "entry1_C");
  GLADE_HOOKUP_OBJECT (modification, label42, "label42");
  GLADE_HOOKUP_OBJECT (modification, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (modification, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (modification, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (modification, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (modification, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (modification, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (modification, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (modification, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (modification, label45, "label45");
  GLADE_HOOKUP_OBJECT (modification, label46, "label46");
  GLADE_HOOKUP_OBJECT (modification, label43, "label43");
  GLADE_HOOKUP_OBJECT (modification, label41, "label41");
  GLADE_HOOKUP_OBJECT (modification, label40, "label40");
  GLADE_HOOKUP_OBJECT (modification, label21, "label21");
  GLADE_HOOKUP_OBJECT (modification, label24, "label24");
  GLADE_HOOKUP_OBJECT (modification, label22, "label22");
  GLADE_HOOKUP_OBJECT (modification, label20, "label20");
  GLADE_HOOKUP_OBJECT (modification, button1_r, "button1_r");
  GLADE_HOOKUP_OBJECT (modification, button2_VAL, "button2_VAL");
  GLADE_HOOKUP_OBJECT (modification, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (modification, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modification, image11, "image11");
  GLADE_HOOKUP_OBJECT (modification, label23, "label23");
  GLADE_HOOKUP_OBJECT (modification, label_introuvable_modif, "label_introuvable_modif");

  return modification;
}

GtkWidget*
create_recherche (void)
{
  GtkWidget *recherche;
  GtkWidget *fixed10;
  GtkWidget *entry1_cin;
  GtkWidget *label30;
  GtkWidget *label25;
  GtkWidget *button1_rech1;
  GtkWidget *image17;
  GtkWidget *treeview3;

  recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (recherche), _("recherche"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (recherche), fixed10);

  entry1_cin = gtk_entry_new ();
  gtk_widget_show (entry1_cin);
  gtk_fixed_put (GTK_FIXED (fixed10), entry1_cin, 144, 48);
  gtk_widget_set_size_request (entry1_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_cin), 8226);

  label30 = gtk_label_new (_("cin"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed10), label30, 48, 48);
  gtk_widget_set_size_request (label30, 72, 33);

  label25 = gtk_label_new (_("voila les informations d'etudiant choisit:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed10), label25, 8, 8);
  gtk_widget_set_size_request (label25, 384, 40);

  button1_rech1 = gtk_button_new ();
  gtk_widget_show (button1_rech1);
  gtk_fixed_put (GTK_FIXED (fixed10), button1_rech1, 312, 48);
  gtk_widget_set_size_request (button1_rech1, 66, 29);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (button1_rech1), image17);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview3, 0, 144);
  gtk_widget_set_size_request (treeview3, 600, 296);

  g_signal_connect ((gpointer) button1_rech1, "clicked",
                    G_CALLBACK (on_button1_rech1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (recherche, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (recherche, entry1_cin, "entry1_cin");
  GLADE_HOOKUP_OBJECT (recherche, label30, "label30");
  GLADE_HOOKUP_OBJECT (recherche, label25, "label25");
  GLADE_HOOKUP_OBJECT (recherche, button1_rech1, "button1_rech1");
  GLADE_HOOKUP_OBJECT (recherche, image17, "image17");
  GLADE_HOOKUP_OBJECT (recherche, treeview3, "treeview3");

  return recherche;
}

GtkWidget*
create_option (void)
{
  GtkWidget *option;
  GtkWidget *fixed11;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *label48;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *button2_cal;
  GtkWidget *label49;
  GtkWidget *label50;

  option = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (option), _("option"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (option), fixed11);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("3 eme annee"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton3, 16, 160);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("4 eme annee"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton4, 16, 192);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("5 eme annee"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton5, 16, 224);
  gtk_widget_set_size_request (checkbutton5, 118, 24);

  label48 = gtk_label_new (_("nombre des etudiants par niveau"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed11), label48, 72, 16);
  gtk_widget_set_size_request (label48, 272, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("1 ere annee"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton1, 16, 96);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("2 eme annee"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton2, 16, 128);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  button2_cal = gtk_button_new_with_mnemonic (_("calculer"));
  gtk_widget_show (button2_cal);
  gtk_fixed_put (GTK_FIXED (fixed11), button2_cal, 144, 256);
  gtk_widget_set_size_request (button2_cal, 66, 29);

  label49 = gtk_label_new ("");
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed11), label49, 176, 128);
  gtk_widget_set_size_request (label49, 192, 96);

  label50 = gtk_label_new_with_mnemonic (_("voila le nombre d'etudiant:\n"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed11), label50, 160, 88);
  gtk_widget_set_size_request (label50, 192, 16);

  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5, "toggled",
                    G_CALLBACK (on_checkbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) button2_cal, "clicked",
                    G_CALLBACK (on_button2_cal_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (option, option, "option");
  GLADE_HOOKUP_OBJECT (option, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (option, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (option, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (option, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (option, label48, "label48");
  GLADE_HOOKUP_OBJECT (option, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (option, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (option, button2_cal, "button2_cal");
  GLADE_HOOKUP_OBJECT (option, label49, "label49");
  GLADE_HOOKUP_OBJECT (option, label50, "label50");

  return option;
}

GtkWidget*
create_suppression_succes (void)
{
  GtkWidget *suppression_succes;
  GtkWidget *fixed12;
  GtkWidget *label53;

  suppression_succes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (suppression_succes), _("suppression_succes"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (suppression_succes), fixed12);

  label53 = gtk_label_new (_("<span foreground =\"green\"><b>suppression effectuee avec succes</b></span>"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed12), label53, 32, 64);
  gtk_widget_set_size_request (label53, 264, 40);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label53), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suppression_succes, suppression_succes, "suppression_succes");
  GLADE_HOOKUP_OBJECT (suppression_succes, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (suppression_succes, label53, "label53");

  return suppression_succes;
}

GtkWidget*
create_modification_succes (void)
{
  GtkWidget *modification_succes;
  GtkWidget *fixed13;
  GtkWidget *label54;

  modification_succes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modification_succes), _("modification_succes"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (modification_succes), fixed13);

  label54 = gtk_label_new (_("<span  foreground =\"green\"><b>modification effectuee avec succes!! </b></span>"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed13), label54, 8, 40);
  gtk_widget_set_size_request (label54, 304, 104);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modification_succes, modification_succes, "modification_succes");
  GLADE_HOOKUP_OBJECT (modification_succes, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (modification_succes, label54, "label54");

  return modification_succes;
}

