/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_inscription (void);
GtkWidget* create_authen (void);
GtkWidget* create_espace_foyer (void);
GtkWidget* create_ajout (void);
GtkWidget* create_SUPPRIMER (void);
GtkWidget* create_error (void);
GtkWidget* create_modification (void);
GtkWidget* create_recherche (void);
GtkWidget* create_option (void);
GtkWidget* create_suppression_succes (void);
GtkWidget* create_modification_succes (void);
