/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "fonction.h"

int
main (int argc, char *argv[])
{
 GtkWidget *inscription;
  GtkWidget *authen;
  GtkWidget *espace_foyer;
  GtkWidget *ajout;
  GtkWidget *SUPPRIMER;
  GtkWidget *index;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*inscription = create_inscription ();
  gtk_widget_show (inscription);*/
  authen = create_authen ();
  gtk_widget_show (authen);
 /*espace_foyer = create_espace_foyer ();
  gtk_widget_show (espace_foyer);
  index=gtk_image_new_from_file(" ./images/index.png");
  
  ajout = create_ajout ();
  gtk_widget_show (ajout);
  SUPPRIMER = create_SUPPRIMER ();
  gtk_widget_show (SUPPRIMER);
*/
  gtk_main ();
  return 0;
}

